#!/usr/bin/env ruby
require 'shellwords'
require 'readline'
require 'rubygems'
require 'colored'
require 'pry'


class Shirt

  #Store terminal state
  stty_save = `stty -g`.chomp

  BUILTINS = {
    'cd'     => lambda { |dir  = ENV["HOME"]| Dir.chdir(dir) },
    'exit'   => lambda { |code = 0| exit(code.to_i) },
    'exec'   => lambda { |*command| exec *command },
    'reload' => lambda {  exec './shirt'}
  }

  def self.d_dir
    return Dir.pwd.gsub(ENV["HOME"],"~").green
  end

  begin
    while line = Readline.readline("[".white+"#{$$}".magenta+"]".white+"[#{d_dir()}]: ".white, true)
      command, *arguments = Shellwords.shellsplit(line)

      redo if line.empty? 

      if BUILTINS[command]
        begin
          BUILTINS[command].call(*arguments)
        rescue StandardError => e
          $stderr.puts e.to_s.red
        end
      else
        pid = fork {
          begin
            exec line
          rescue StandardError => e
            $stderr.puts e.to_s.red
          end
        }

        Process.wait pid
      end
    end
  rescue Interrupt => e
    system("stty", stty_save)
  end
end
